# PRE SPRAVNU FUNKCIU MUSI BYT DEFINOVANY .env KTORY POUZIJE PODLA .env.docker.example
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - app_assets:/var/www/public/build
      - image_assets:/var/www/public/images

    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  webserver:
    build:
      context: ./nginx_config
      dockerfile: Dockerfile
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - app_assets:/var/www/public/build
      - image_assets:/var/www/public/images
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33077:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app_assets:
    driver: local
  image_assets:
    driver: local